config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'boards/index'
  get 'boards/show/:id' => 'boards#show'
  post 'boards/create' => 'boards#create'

  post 'comments/create' => 'comments#create'

  root 'rooms#index'
  resources :rooms, only: %i[show]

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    belongs_to :room
    belongs_to :user
    has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :board
end

app/models/message.rb
class Message < ApplicationRecord
    validates :content, presence: true

    # createの後にコミットする { MessageBroadcastJobのperformを遅延実行 引数はself }
    after_create_commit { MessageBroadcastJob.perform_later self }
    
    belongs_to :user
    belongs_to :room
end

app/models/my_class.rb
class MyClass < ApplicationRecord
    # def self.import(file)
    #   CSV.foreach(file.path, headers: true) do |row|
    #     book = find_by(id: row["id"]) || new
    #     book.attributes = row.to_hash.slice(*updatable_attributes)
    #     book.save!(validate: false)
    #   end
    # end
    #
    # def self.updatable_attributes
    #   ['id', 'title', 'body']
    # end

    def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
        # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
        user = find_by(id: row["id"]) || new
        # CSVからデータを取得し、設定する
        user.attributes = row.to_hash.slice(*updatable_attributes)

        # ↓追加
        # @post = Post.new(
        #   content: params[:content],
        #   user_id: @current_user.id
        # )
        # Post.new(
        #   content: params[:content],
        #   user_id: @current_user.id
        # )
        # ↑追加ここまで

        # 保存する
        user.save
      end
    end

    # 更新を許可するカラムを定義
    def self.updatable_attributes
      ["id", "course_number", "user_id"]
    end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
    has_many :boards
end

app/models/sub.rb
# class Sub < ApplicationRecord
# end

class Sub < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      sub = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      sub.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      sub.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "course_number"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :boards
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  def index

  end

  # def register
  #   @myclasses = MyClass.all
  # end

  # def import
  #   # fileはtmpに自動で一時保存される
  #   Sub.import(params[:file])
  #   # redirect_to boards_url
  #   redirect_to boards_register_path(@user)
  #   #どっちか
  #   # redirect_to boards_register_path
  # end

  # dbにuser_idの追加

  def register
    @subs = Sub.all
  end

  def import
    # fileはtmpに自動で一時保存される
    Sub.import(params[:file])
    # redirect_to boards_register_path
    # redirect_to boards_register_path(@user.id)
    redirect_to boards_register_path(current_user.id)
    #   #どっちか
  end


  def create
    @post = Post.new(
      content: params[:content],
      user_id: @current_user.id
    )
  end

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to controller: :boards, action: :show, id: @comment.board_id
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :board_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @rooms = Room.all.order(:id)
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# class Users::OmniauthCallbacksController < ApplicationController
# end

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_from :twitter
  end

  private
  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      print("persisted true")
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      print("persisted false")
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to controller: 'sessions', action: 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # マイページ
  def show
    @user = User.find(params[:id])
    @userida = current_user.id
    # render template: 'boards/index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.erb
<div>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  <div class="container text-center">
    <button type="button" class="btn btn-primary mt-5" data-toggle="modal" data-target="#board">質問を投稿する</button>
    <div class="modal fade" id="board" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <%= form_for(@board, url: boards_create_path, method: :post) do |f| %>
            <div class="modal-body">
              <%= f.text_field :title, class: "form-control", placeholder: "質問タイトル", :required => true %>
              <%= f.text_field :content, class: "form-control", placeholder: "質問内容", :required => true %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :room_id, :value => @room.id %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
              <%= f.submit "投稿する", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid text-center">
    <div class="row">
      <% @boards.each do |board| %>
        <div class="col-md-4" style="padding:10px;">
            <h3><%= link_to "#{board.title}", "/boards/show/#{board.id}" %></h3>
            <p>質問者: <%= "#{board.user.email}" %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/register.html.erb
<!-- <h1>Boards#register</h1>
<p>Find me in app/views/boards/register.html.erb</p> -->
<h1>授業登録</h1>
<p>~twinsから取得したcsvをインポートできます~</p>


<h1>授業一覧（仮）</h1>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>授業番号</th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |subs| %>
      <tr>
        <td><%= subs.id %></td>
        <td><%= subs.course_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= form_tag import_boards_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>

app/views/boards/show.html.erb
<div>
    <h2>質問タイトル: <%= @board.title %></h2>
    <h2>質問内容: <%= @board.content %></h2>
<div>
    <%= form_for(@comment, url: comments_create_path, method: :post) do |f| %>
        <div>
            <%= f.text_field :body, class: "form-control", placeholder: "アドバイス", :required => true %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :board_id, :value => @board.id %>
        </div>
        <div>
            <%= f.submit "投稿" %>
        </div>
    <% end %>
</div>

<div id="comments">
    <%= render @comments %>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
    <p><%= "#{comment.user.email}: #{comment.body}" %></p>
</div>

app/views/home/top.html.erb
<h1>Tiita</h1>
<br>
<p>~みんなでわからないを解決~</p>

<!-- <p>ログイン完成させるまで寝ない</p> -->

<% if user_signed_in? %>
  <%= link_to 'logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Twitter登録はこちら', user_twitter_omniauth_authorize_path %>
<% end %>

app/views/rooms/index.html.erb
<div>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  <table>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= "#{room.name}" %></td>
        <td><%= link_to "チャット", room_path(room), data: {"turbolinks" => false}%></td>
        <td><%= link_to "質問スレッド", boards_index_path(room.id)%></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/rooms/show.html.erb
<!--
<h1>Chat Room</h1>
<div id="messages">
    <%= render @messages %>
</div>

<%= label_tag :content, 'Say something:' %>
<%= text_field_tag :content, nil, data: { behavior: 'room_speaker' } %>
-->
<h1>Chat Room</h1>
<!--
<form>
    <div>
        <input type="text" class="chat-input" id="chat-input" />
    </div>
    <button id="button">送信</button>
</form>
-->
<p><%= link_to "授業一覧に戻る", '/', data: {"turbolinks" => false} %></p>
<div class="container text-center">
    <%= label_tag :content, 'ぼやく:' %>
    <%= text_field_tag :content, nil, data: { behavior: 'room_speaker' } %>
</div>
<div id="messages" data-room_id="<%= @room.id %>" class="container text-center">
    <%= render @messages %>
</div>

app/views/users/show.html.erb
<!-- マイページ -->
<!-- <h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p> -->
<h1>マイページ</h1>
<p>~授業の登録をしよう~</p>

<!-- /app/views/user/usershow.html.erb -->

<p>MyUserIDPage(あなたのユーザーIDです): <%= @userida %></p>
<br><br>

<!-- 授業登録画面に遷移 -->
<%= link_to '授業登録',boards_register_path(current_user.id) %>
<br>
<%= link_to 'Twinsからcsvファイルを取得する','https://twins.tsukuba.ac.jp'%>